---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp bietet Ihnen in jeder Version der Keystone STaaS-Dienste neue und verbesserte Funktionen. 
---
= Was ist neu in Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die neuesten Funktionen und Verbesserungen der Keystone STaaS-Dienste.



[[20-july-2026]]
== 20. Juli 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[view-subscription-expiry-and-auto-renewal-status]]
=== Ablauf des Abonnements und Status der automatischen Verlängerung

Die Spalte *Tage bis zum Ablauf des Abonnements* in der Abonnementtabelle (*Storage > Keystone > Subscriptions*) zeigt nun neben dem Ablaufdatum ein Symbol an. Die Symbolfarbe gibt die Nähe des Ablaufs an, wenn die automatische Verlängerung deaktiviert ist: grün (>120 Tage), orange (91–120 Tage), rot (<90 Tage) oder grau (abgelaufen). Bei Abonnements mit aktivierter automatischer Verlängerung wird ein Symbol für die automatische Verlängerung angezeigt, das darauf hinweist, dass sich das Abonnement am Ende der aktuellen Laufzeit automatisch verlängert. Der Status ist schreibgeschützt und spiegelt Ihre Vertragsbedingungen wider. Nach dem Öffnen eines Abonnements erscheinen diese Symbole in der Kopfzeile der Abonnementdetails auf den Registerkarten *Aktueller Verbrauch*, *Verbrauchstrend*, *Abonnement-Timeline* und *Assets*, sodass der Ablauf- und Verlängerungsstatus beim Navigieren sichtbar ist.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/keystone-staas/integrations/subscriptions-tab.html["Details zu Ihren Keystone -Abonnements anzeigen"].



[[29-june-2026]]
== 29. Juni 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[view-adp-license-distribution-for-metrocluster-subscriptions]]
=== ADP-Lizenzverteilung für MetroCluster Abonnements anzeigen

Auf der Registerkarte *Erweiterter Datenschutz (ADP)* ist jetzt ein neuer Unterreiter *Lizenzverteilung* verfügbar, der Einblick in die ADP-Lizenznutzung in Ihren MetroCluster Partnerclustern bietet. Weitere Informationen sind unter link:./integrations/adp-tab.html["Verbrauch und Status Ihrer Keystone MetroCluster Abonnements einsehen"] zu finden.



[[view-ransomware-protection-status-for-your-volumes]]
=== Ransomware-Schutzstatus für Ihre Volumes

Die Registerkarte *Volumes in Clustern* unter *Assets* enthält jetzt eine Spalte *ARP-Status*, die anzeigt, ob der Autonomous Ransomware Protection (ARP) für jedes Volume aktiviert oder deaktiviert ist, wodurch Transparenz über den Ransomware-Schutzstatus aller verwalteten Assets entsteht. Weitere Informationen zu ARP finden sich unter link:https://docs.netapp.com/us-en/ontap/anti-ransomware/["Autonomous Ransomware Protection (ARP) in ONTAP"].



[[share-feedback-using-the-feedback-tab]]
=== Feedback kann über die Registerkarte „Feedback“ geteilt werden.

Sie können nun von jedem Bildschirm im Keystone Dashboard aus Feedback geben, indem Sie die neue Registerkarte *Feedback* verwenden, die am unteren rechten Bildschirmrand verankert ist. Ein Klick darauf öffnet ein Fenster, in dem Sie Ihre Erfahrungen mitteilen und Kommentare direkt an NetApp senden können.



[[improve-alerting-for-capacity-usage-and-subscription-expiration]]
=== Verbesserte Benachrichtigungen für Kapazitätsauslastung und Abonnementablauf

Systemgenerierte Monitore bieten jetzt detailliertere Warnmeldungen zur Kapazitätsauslastung und zum Ablauf von Abonnements.

Bei Ablauf des Abonnements werden nun Warnungen bei fünf Schwellenwerten ausgelöst: 180, 90, 60, 30 und 7 Tage vor Ablauf, wobei der Schweregrad mit Annäherung an das Datum von informativ zu kritisch ansteigt.

Bei der Kapazitätsauslastung basiert der Schwellenwert für die Warnung bei Lastspitzen nun auf dem im Abonnement festgelegten Prozentsatz der zugesicherten Lastspitze anstatt auf einem festen Wert von 20 %. Wenn Ihre zugesicherte Lastspitze beispielsweise 40 % beträgt, wird die kritische Warnung bei 140 % der zugesicherten Kapazitätsauslastung ausgelöst.

Weitere Informationen sind unter link:./integrations/monitoring-alert-monitors.html["Anzeigen und Erstellen von Warnmonitoren für Keystone -Abonnements"] zu finden.



[[25-may-2026]]
== 25. Mai 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[improved-display-of-multiple-updates-on-the-same-day-in-the-subscription-timeline]]
=== Verbesserte Darstellung mehrerer Aktualisierungen am selben Tag in der Abonnement-Timeline

Die Abonnement-Zeitleiste zeigt nun eine Zahl an, wenn mehrere Abonnementaktualisierungen unterschiedlicher Art am selben Tag erfolgen, anstatt separater Symbole. Bewegen Sie den Mauszeiger über die Zahl, um alle Aktualisierungstypen dieses Tages anzuzeigen. Der heruntergeladene Bericht enthält für jede Aktualisierung eine separate Zeile und bietet Ihnen eine vollständige Übersicht aller Änderungen. Weitere Informationen finden Sie unter link:./integrations/subscription-timeline.html["Sehen Sie sich die Zeitleiste Ihrer Keystone -Abonnements an"].



[[27-april-2026]]
== 27. April 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[renamed-provisioned-capacity-label]]
=== Umbenanntes Label für bereitgestellte Kapazität

Die Bezeichnung *Bereitgestellte Kapazität* wurde in *Bereitgestellte Volumenkapazität* umbenannt. Die aktualisierte Bezeichnung wird auch in den zugehörigen CSV- und Excel-Berichten berücksichtigt.



[[forecast-toggle-for-accrued-burst]]
=== Prognoseumschalter für aufgelaufene Burst-Nutzung

Sie können jetzt die *Prognose*-Funktion in der Ansicht *Aufgelaufener Burst* auf der Registerkarte *Verbrauchstrend* nutzen, um den aufgelaufenen Burst-Verbrauch für die nächsten 120 Tage ab dem aktuellen Datum zu prognostizieren. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-forecast-data["Prognosedaten anzeigen"].



[[30-march-2026]]
== 30. März 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[above-burst-capacity-on-the-historical-consumption-chart]]
=== Oberhalb der Spitzenkapazität im historischen Verbrauchsdiagramm

Das Diagramm zum historischen Verbrauch im Tab *Verbrauchstrend* hebt nun Verbrauch hervor, der das Burst-Limit überschreitet. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html["Verbrauchstrends Ihrer Keystone -Abonnements anzeigen"].



[[forecast-for-capacity-usage]]
=== Prognose für die Kapazitätsauslastung

Sie können die *Prognose*-Funktion in der Ansicht *Historischer Verbrauch* auf der Registerkarte *Verbrauchstrend* nutzen, um die Kapazitätsauslastung für die nächsten 120 Tage ab dem aktuellen Datum zu prognostizieren. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-forecast-data["Prognosedaten anzeigen"].



[[tracking-id-in-subscription-export]]
=== Tracking-ID im Abonnement-Export

Der von der Seite *Abonnements* heruntergeladene Abonnementbericht enthält nun die *Tracking ID* in den Leistungsdaten auf Serviceebene sowohl im Excel- als auch im CSV-Format.



[[subscriptions-page-column-visibility-updates]]
=== Aktualisierungen der Spaltensichtbarkeit auf der Abonnementseite

Auf der Seite *Abonnements* ist die Spalte *Keystone-Version* jetzt standardmäßig ausgeblendet, und die Spalte *Verknüpfte Abonnements* wird nur angezeigt, wenn verknüpfte Abonnements verfügbar sind.



[[march-02-2026]]
== 2. März 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[new-columns-in-the-volumes-in-clusters-tab]]
=== Neue Spalten auf der Registerkarte Volumes in clusters

Drei neue Spalten, *Hot data*, *Cold tier (%)* und *Hot tier (%)*, wurden dem Tab *Volumes in clusters* in *Assets* hinzugefügt. Weitere Informationen finden Sie unter link:./integrations/assets-tab.html["Anzeigen von Assets, die mit einem Keystone -Abonnement verknüpft sind"] und link:./integrations/assets.html["Anzeigen von Assets in allen Ihren Keystone -Abonnements"].



[[invoiced-uninvoiced-and-provisional-burst-usage-in-consumption-trend]]
=== Fakturierte, nicht fakturierte und vorläufige Spitzennutzung im Verbrauchstrend

Das Diagramm zur aufgelaufenen Burst-Abrechnung im Tab *Consumption trend* zeigt jetzt abgerechnete, nicht abgerechnete und vorläufige Burst-Nutzung an. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-accrued-burst["Aufgelaufenen Burst anzeigen"].



[[enhancements-to-the-monitoring-view]]
=== Verbesserungen an der Überwachungsansicht

Die *Monitoring*-Ansicht umfasst die folgenden Aktualisierungen:

* *Registerkarte „Alerts“*: Die Spalte *Alert* wurde in *Alert type & condition* umbenannt. Sie können jetzt auch das Auslassungspunkte-Symbol neben der Spalte *Status* verwenden, um einen Alert zu bearbeiten, eine Notiz hinzuzufügen oder Alert-Details anzuzeigen.
* *Registerkarte Warnmonitore*: Die Spalte *Bedingung* wurde in *Überwachungstyp & Bedingung* umbenannt.


Weitere Informationen finden Sie unter link:./integrations/monitoring-alerts.html["Anzeigen und Verwalten von Benachrichtigungen für Keystone -Abonnements"] und link:./integrations/monitoring-alert-monitors.html["Anzeigen und Erstellen von Warnmonitoren für Keystone -Abonnements"].



[[16-february-2026]]
== 16. Februar 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[dii-add-on-consumption-display]]
=== DII Add-on-Verbrauchsanzeige

Der Data Infrastructure Insights (DII) Add-on-Verbrauch wird jetzt in den Tabs *Aktueller Verbrauch* und *Verbrauchstrend* angezeigt. Weitere Informationen finden Sie unter link:./concepts/data-infra-insights.html#view-dii-consumption["DII consumption anzeigen"].



[[02-february-2026]]
== 02. Februar 2026

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[interactive-filtering-for-daily-accrued-burst-data]]
=== Interaktive Filterung für täglich akkumulierte Burst-Daten

Die Tabelle *Accrued burst by days* im Tab *Consumption trend* unterstützt jetzt interaktives Filtern. Wählen Sie einen beliebigen Balken im Diagramm der aufgelaufenen Ausfälle aus, um nur die Tage innerhalb dieses Abrechnungszeitraums anzuzeigen. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["Täglich aufgelaufene Burst-Datennutzung anzeigen"].



[[enhanced-date-range-display-in-accrued-burst-graph]]
=== Erweiterte Datumsbereichsanzeige im Diagramm der kumulierten Ausbrüche

Das Diagramm der aufgelaufenen Spitzenabrechnungen im Tab *Consumption trend* zeigt jetzt für jeden Abrechnungszeitraum vollständige Datumsbereiche an, wie zum Beispiel 01. Okt 2025 bis 31. Okt 2025, anstatt nur Monat und Jahr.



[[expandable-subscription-details-view]]
=== Erweiterbare Ansicht der Abonnementdetails

Die Registerkarte *Abonnements* enthält eine Option, um alle Abonnements zu erweitern und gleichzeitig Informationen zu den Performance-Servicelevels für jedes Abonnement anzuzeigen. Weitere Informationen finden Sie unter link:./integrations/subscriptions-tab.html["Details zu Ihren Keystone -Abonnements anzeigen"].



[[new-usage-type-column]]
=== Neue Spalte Nutzungstyp

Die Registerkarte *Abonnements* enthält eine Spalte *Nutzungstyp*, die anzeigt, ob das Abonnement auf Basis der bereitgestellten, physischen oder logischen Nutzung abgerechnet wird. Weitere Informationen finden Sie unter link:./integrations/subscriptions-tab.html["Details zu Ihren Keystone -Abonnements anzeigen"].



[[08-december-2025]]
== 8. Dezember 2025

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[renamed-accrued-burst-capacity-label]]
=== Umbenannt in „Aufgelaufene Auslösekapazität“

Die Bezeichnung *Accrued burst capacity* wird in *Accrued burst* umbenannt.



[[24-november-2025]]
== 24. November 2025

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[tracking-id-for-coverage-gap-subscriptions]]
=== Tracking-ID für Abonnements mit Abdeckungslücke

Im Benachrichtigungsfeld *Vervollständigen Sie Ihre Abdeckung* unter *Überwachung > Alarmmonitore* wird nun für jedes Abonnement neben der Abonnementnummer die Tracking-ID angezeigt.



[[10-november-2025]]
== 10. November 2025

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[complete-your-coverage-notification-box]]
=== Füllen Sie Ihr Feld für die Versicherungsbenachrichtigung aus.

Auf der Seite „Überwachung“ befindet sich unter dem Reiter „Warnungen“ ein Benachrichtigungsfeld mit der Aufschrift „Vervollständigen Sie Ihre Abdeckung“, das erscheint, wenn Abdeckungslücken bestehen. In dieser Box werden Abonnements aufgelistet, bei denen Kapazitäts- oder Ablaufüberwachungen fehlen, sowie Überwachungen ohne Abonnements. Sie können die Lücken schließen, indem Sie bestehenden Monitoren Abonnements hinzufügen, neue Monitore erstellen oder nicht verwendete Monitore löschen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["Abdeckungslücken für Alarmmonitore verwalten"].



[[13-october-2025]]
== 13. Oktober 2025

Neue Verbesserungen im Keystone -Dashboard in der NetApp Console:



[[qos-policy-override-column-in-assets-tab]]
=== Spalte „QoS-Richtlinie außer Kraft setzen“ auf der Registerkarte „Assets“

Die Registerkarte *Volumes in Clustern* innerhalb der Registerkarte *Assets* enthält jetzt eine Spalte *Außerkraftsetzung der QoS-Richtlinie*, die angibt, ob QoS-Regeln für Sicherungs- und Spiegelvolumes umgangen werden. Dabei wird *true* (Regeln ignoriert), *false* (Regeln erzwungen) oder *N/A* (für Spiegelvolumes) angezeigt.


NOTE: Bei Keystone v3-Abonnements wird in dieser Spalte *N/A* angezeigt, da QoS-Richtlinien im v3-Angebot nicht anwendbar sind.



[[enhanced-alerts-visibility-in-overview-page]]
=== Verbesserte Sichtbarkeit von Warnungen auf der Übersichtsseite

Die Seite *Übersicht* enthält jetzt zwei neue Warnabschnitte mit den Namen *Ungelöste Warnmeldungen nach Schweregrad* und *Älteste ungelöste Keystone Warnmeldungen*. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-console.html["Keystone -Dashboard in der NetApp -Konsole"] .



[[06-october-2025]]
== 06. Oktober 2025



[[bluexp-is-now-netapp-console]]
=== BlueXP heißt jetzt NetApp Console

Die NetApp Console basiert auf der verbesserten und neu strukturierten BlueXP -Grundlage und ermöglicht die zentrale Verwaltung von NetApp Storage und NetApp Data Services in On-Premises- und Cloud-Umgebungen auf Unternehmensniveau. Sie liefert Einblicke in Echtzeit, schnellere Workflows und eine vereinfachte Administration mit hoher Sicherheit und Konformität.

Einzelheiten zu den Änderungen finden Sie imlink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Versionshinweise zur NetApp Konsole"^] .



[[22-september-2025]]
== 22. September 2025



[[addition-of-alert-monitoring]]
=== Hinzufügen einer Alarmüberwachung

Das Keystone -Dashboard in BlueXP enthält jetzt eine Registerkarte „Überwachung“ zum Verwalten von Warnungen und Monitoren für Ihre Abonnements. Mit dieser neuen Registerkarte können Sie:

* Zeigen Sie aktive Warnungen an und lösen Sie diese, darunter sowohl systemgenerierte als auch benutzerdefinierte Warnungen zur Kapazitätsnutzung und zum Ablauf von Abonnements.
* Erstellen Sie Warnmonitore, um die Kapazitätsnutzung und den Ablauf von Abonnements zu verfolgen.


Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/keystone-staas-2/integrations/monitoring-alerts.html["Anzeigen und Verwalten von Warnungen und Monitoren"] .



[[streamlined-performance-service-levels-viewing]]
=== Optimierte Anzeige der Leistungsservice-Level

Sie können die Informationen zu den Leistungsserviceleveln, die jetzt von einer separaten Registerkarte in eine erweiterbare Ansicht verschoben wurden, auf der Registerkarte *Abonnements* anzeigen. Klicken Sie auf den Abwärtspfeil neben der Spalte *Ablaufdatum*, um sie für jedes Abonnement anzuzeigen. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/keystone-staas-2/integrations/subscriptions-tab.html["Details zu Ihren Keystone -Abonnements anzeigen"] .



[[28-august-2025]]
== 28. August 2025



[[enhanced-logical-usage-tracking-with-a-new-column]]
=== Verbesserte logische Nutzungsverfolgung mit einer neuen Spalte

Eine neue Spalte, Gesamt-Footprint, wurde hinzugefügt, um die Keystone Verbrauchsverfolgung für FabricPool -Volumes zu verbessern:

* * Keystone -Dashboard in BlueXP*: Sie können die Spalte *Gesamt-Footprint* auf der Registerkarte *Volumes in Clustern* innerhalb der Registerkarte *Assets* sehen.
* * Digital Advisor*: Sie können die Spalte *Gesamt-Footprint* auf der Registerkarte *Volume-Details* innerhalb der Registerkarte *Volumes & Objekte* sehen.


Diese Spalte zeigt den gesamten logischen Footprint für Volumes mit FabricPool -Tiering an, einschließlich Daten aus Leistungs- und Cold-Tiers, sodass Sie den Keystone -Verbrauch genau berechnen können.



[[05-august-2025]]
== 05. August 2025



[[view-instance-level-consumption-data]]
=== Anzeigen von Verbrauchsdaten auf Instanzebene

Sie können den aktuellen Verbrauch und historische Daten für jede Instanz des Performance-Service-Levels über das Keystone -Dashboard in BlueXP anzeigen.  Diese Funktion ist für Leistungsservicelevel mit mehreren Instanzen verfügbar, sofern Sie über ein Abonnement für Keystone Version 3 (v3) verfügen.  Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["Den Verbrauch Ihrer Keystone -Abonnements anzeigen"] .



[[30-june-2025]]
== 30. Juni 2025



[[keystone-version-3-v3-release]]
=== Veröffentlichung von Keystone Version 3 (v3).

Sie können jetzt Keystone Version 3 (v3) abonnieren, die neueste Version des NetApp Keystone STaaS-Angebots.  Diese Version führt mehrere Verbesserungen ein, darunter vereinfachte Leistungsservicelevel, zusätzliche Burst-Kapazitätsoptionen und flexible Abrechnungsfrequenzen.  Diese Verbesserungen vereinfachen die Verwaltung, Optimierung und Skalierung von Speicherlösungen.  Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/keystone-staas/concepts/metrics.html["Keystone STaaS-Dienste für v3"] .

Sie können sich an das Keystone Supportteam wenden, um Keystone Version 3 (v3) zu abonnieren. Weitere Einzelheiten finden Sie unter link:https://docs.netapp.com/us-en/keystone-staas/concepts/support-services.html["Holen Sie sich Hilfe zu Keystone"]Die



[[19-june-2025]]
== 19. Juni 2025



[[keystone-dashboard-in-bluexp]]
=== Keystone Dashboard in BlueXP

Sie können jetzt direkt von BlueXP aus auf das Keystone -Dashboard zugreifen.  Diese Integration bietet Ihnen einen zentralen Ort zum Überwachen, Verwalten und Verfolgen aller Ihrer Keystone -Abonnements sowie Ihrer anderen NetApp -Dienste.

Mit dem Keystone -Dashboard in BlueXP können Sie:

* Zeigen Sie alle Ihre Abonnementdetails, Kapazitätsnutzung und Assets an einem Ort an.
* Verwalten Sie Abonnements ganz einfach und fordern Sie Änderungen an, wenn sich Ihre Anforderungen ändern.
* Bleiben Sie mit den neuesten Informationen zu Ihrer Speicherumgebung auf dem Laufenden.


Um zu beginnen, gehen Sie im linken Navigationsmenü von BlueXP zu *Speicher > Keystone *.  Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Übersicht über das Keystone -Dashboard"] .



[[08-january-2025]]
== 08. Januar 2025



[[addition-of-daily-accrued-data-usage-viewing-options]]
=== Hinzufügen von Anzeigeoptionen für die täglich anfallende Datennutzung

Sie können jetzt den täglich aufgelaufenen Datenverbrauch für einen monatlichen oder vierteljährlichen Abrechnungszeitraum entweder im Diagramm- oder Tabellenformat anzeigen, indem Sie auf die Leiste klicken, die die in Rechnung gestellten Daten anzeigt.  Weitere Informationen finden Sie unterlink:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["Täglich aufgelaufene Burst-Datennutzung anzeigen"] .



[[12-december-2024]]
== 12. Dezember 2024



[[renamed-logical-used-column]]
=== Spalte „Logisch verwendet“ umbenannt

Die Spalte *Logical Used* auf der Registerkarte *Volume Details* unter *Volumes & Objects* wurde jetzt in * Keystone Logical Used* umbenannt.



[[enhanced-assets-tab]]
=== Registerkarte „Erweiterte Assets“

Die Registerkarte *Assets* im Bildschirm * Keystone -Abonnements* verfügt jetzt über zwei neue Unterregisterkarten: * ONTAP* und * StorageGRID*.  Diese Unterregisterkarten bieten basierend auf Ihren Abonnements detaillierte Einblicke auf Clusterebene für ONTAP und Informationen auf Grid-Ebene für StorageGRID .  Weitere Informationen finden Sie unterlink:./integrations/assets-tab.html["Registerkarte „Assets“"^] .



[[new-hideshow-columns-option]]
=== Neue Option zum Ausblenden/Anzeigen von Spalten

Die Registerkarte *Volumedetails* in *Volumes & Objekte* enthält jetzt die Option *Spalten ausblenden/einblenden*.  Mit dieser Option können Sie Spalten auswählen oder abwählen, um die tabellarische Auflistung der Datenträger nach Ihren Wünschen anzupassen.  Weitere Informationen finden Sie unterlink:./integrations/volumes-objects-tab.html["Registerkarte „Volumes und Objekte“"^] .



[[21-november-2024]]
== 21. November 2024



[[enhanced-invoiced-accrued-burst]]
=== Erweiterter, in Rechnung gestellter, aufgelaufener Burst

Sie können jetzt die aufgelaufenen Burst-Nutzungsdaten vierteljährlich über die Option *Invoiced Accrued Burst* anzeigen, wenn Sie sich für einen vierteljährlichen Abrechnungszeitraum entschieden haben.  Weitere Informationen finden Sie unterlink:./integrations/consumption-tab.html#view-accrued-burst["Abgerechneten aufgelaufenen Burst anzeigen"^] .



[[new-columns-in-the-volumes-details-tab]]
=== Neue Spalten auf der Registerkarte „Volumes Details“

Um die Berechnung der logischen Nutzung übersichtlicher zu gestalten, wurden der Registerkarte *Volumedetails* innerhalb der Registerkarte *Volumes & Objekte* zwei neue Spalten hinzugefügt:

* *Logisches AFS*: Zeigt die logische Kapazität an, die vom aktiven Dateisystem des Volumes verwendet wird.
* *Physischer Snapshot*: Zeigt den von den Snapshots verwendeten physischen Speicherplatz an.


Diese Spalten bieten eine bessere Übersichtlichkeit in der Spalte *Logical Used*, die die kombinierte logische Kapazität anzeigt, die vom aktiven Dateisystem des Volumes verwendet wird, und den physischen Speicherplatz, der von Snapshots verwendet wird.



[[11-november-2024]]
== 11. November 2024



[[enhanced-report-generation]]
=== Verbesserte Berichterstellung

Sie können jetzt mithilfe der Berichtsfunktion in Digital Advisor einen konsolidierten Bericht erstellen, um die Details Ihrer Keystone -Daten anzuzeigen.  Weitere Informationen finden Sie unterlink:./integrations/options.html#generate-consolidated-report-from-digital-advisor["Konsolidierten Bericht erstellen"^] .



[[10-july-2024]]
== 10. Juli 2024



[[label-modifications]]
=== Etikettenänderungen

Die Bezeichnung *Aktuelle Nutzung* wird in *Aktueller Verbrauch* geändert und *Kapazitätstrend* wird in *Verbrauchstrend* geändert.



[[search-bar-for-subscriptions]]
=== Suchleiste für Abonnements

Das Dropdown-Menü *Abonnements* auf allen Registerkarten im Bildschirm * Keystone -Abonnements* enthält jetzt eine Suchleiste.  Sie können nach bestimmten Abonnements suchen, die im Dropdown-Menü *Abonnements* aufgeführt sind.



[[27-june-2024]]
== 27. Juni 2024



[[consistent-display-of-subscription]]
=== Einheitliche Anzeige des Abonnements

Der Bildschirm „Keystone -Abonnements“ wird aktualisiert, um die ausgewählte Abonnementnummer auf allen Registerkarten anzuzeigen.

* Wenn eine beliebige Registerkarte im Bildschirm „Keystone -Abonnements“ aktualisiert wird, navigiert der Bildschirm automatisch zur Registerkarte „Abonnements“ und setzt alle Registerkarten auf das erste Abonnement zurück, das im Dropdown-Menü „Abonnement“ aufgeführt ist.
* Wenn das ausgewählte Abonnement keine Leistungsmetriken abonniert hat, wird auf der Registerkarte *Leistung* bei der Navigation das erste Abonnement angezeigt, das im Dropdown-Menü *Abonnement* aufgeführt ist.




[[29-may-2024]]
== 29. Mai 2024



[[enhanced-burst-indicator]]
=== Verbesserte Burst-Anzeige

Der *Burst*-Indikator im Index des Nutzungsdiagramms wurde erweitert, um den Prozentwert des Burst-Limits anzuzeigen.  Dieser Wert ändert sich je nach vereinbartem Burst-Limit für ein Abonnement.  Sie können den Burst-Limitwert auch auf der Registerkarte *Abonnements* anzeigen, indem Sie mit der Maus über die Anzeige *Burst-Nutzung* in der Spalte *Nutzungsstatus* fahren.



[[addition-of-service-levels]]
=== Hinzufügen von Service-Levels

Die Service-Levels *CVO Primary* und *CVO Secondary* sind enthalten, um Cloud Volumes ONTAP für Abonnements zu unterstützen, die Tarifpläne mit null zugesagter Kapazität haben oder mit einem Metro-Cluster konfiguriert sind.

* Sie können das Diagramm zur Kapazitätsnutzung für diese Service-Levels im alten Dashboard des Widgets „Keystone -Abonnements“ und auf der Registerkarte „Kapazitätstrend“ sowie detaillierte Nutzungsinformationen auf der Registerkarte „Aktuelle Nutzung“ anzeigen.
* Im Reiter *Abonnements* werden diese Service-Levels angezeigt als `CVO (v2)` in der Spalte *Nutzungstyp*, wodurch die Abrechnung entsprechend dieser Servicelevel identifiziert werden kann.




[[zoom-in-feature-for-short-term-bursts]]
=== Zoom-In-Funktion für kurze Ausbrüche

Die Registerkarte *Kapazitätstrend* enthält jetzt eine Zoomfunktion, um die Details kurzfristiger Ausbrüche in den Nutzungsdiagrammen anzuzeigen. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html["Registerkarte „Kapazitätstrend“"^] .



[[enhanced-display-of-subscriptions]]
=== Verbesserte Anzeige von Abonnements

Die Standardanzeige von Abonnements wurde erweitert, um die Sortierung nach Tracking-ID zu ermöglichen.  Die Abonnements auf der Registerkarte *Abonnements*, einschließlich der Dropdown-Liste *Abonnement* und der CSV-Berichte, werden jetzt basierend auf der alphabetischen Reihenfolge der Tracking-IDs in der Reihenfolge a, A, b, B usw. angezeigt.



[[enhanced-accrued-burst-display]]
=== Verbesserte Anzeige der aufgelaufenen Bursts

Der Tooltip, der angezeigt wird, wenn Sie mit der Maus über das Balkendiagramm zur Kapazitätsnutzung auf der Registerkarte *Kapazitätstrend* fahren, zeigt jetzt den Typ des aufgelaufenen Bursts basierend auf der zugesagten Kapazität an.  Es wird zwischen vorläufigem und in Rechnung gestelltem aufgelaufenem Burst unterschieden und für Abonnements mit Tarifplänen für zugesagte Kapazitäten von null der *vorläufige aufgelaufene Verbrauch* und der *in Rechnung gestellte aufgelaufene Verbrauch* sowie für Abonnements mit zugesagter Kapazität ungleich null der *vorläufige aufgelaufene Burst* und der *in Rechnung gestellte aufgelaufene Burst* angezeigt.



[[09-may-2024]]
== 09. Mai 2024



[[new-columns-in-csv-reports]]
=== Neue Spalten in CSV-Berichten

Die CSV-Berichte auf der Registerkarte *Kapazitätstrend* enthalten jetzt die Spalten *Abonnementnummer* und *Kontoname* für verbesserte Details.



[[enhanced-usage-type-column]]
=== Spalte „Erweiterter Verwendungstyp“

Die Spalte *Verwendungstyp* auf der Registerkarte *Abonnements* wurde erweitert, um logische und physische Verwendungen als durch Kommas getrennte Werte für Abonnements anzuzeigen, die Servicelevel sowohl für Dateien als auch für Objekte abdecken.



[[access-object-storage-details-from-volume-details-tab]]
=== Greifen Sie über die Registerkarte „Volume-Details“ auf Objektspeicherdetails zu

Die Registerkarte *Volumedetails* innerhalb der Registerkarte *Volumes & Objekte* bietet jetzt Objektspeicherdetails sowie Volumeinformationen für Abonnements, die Servicelevel für Dateien und Objekte enthalten.  Sie können auf der Registerkarte *Volume-Details* auf die Schaltfläche *Object Storage-Details* klicken, um die Details anzuzeigen.



[[28-march-2024]]
== 28. März 2024



[[improvement-to-qos-policy-compliance-display-in-the-volume-details-tab]]
=== Verbesserung der Anzeige der QoS-Richtlinienkonformität auf der Registerkarte „Volumedetails“

Die Registerkarte *Volumedetails* innerhalb der Registerkarte *Volumes & Objekte* bietet jetzt eine bessere Übersicht über die Einhaltung der Quality of Service (QoS)-Richtlinie.  Die Spalte, die früher als *AQoS* bekannt war, wurde in *Compliant* umbenannt. Sie gibt an, ob die QoS-Richtlinie konform ist.  Darüber hinaus wurde eine neue Spalte *QoS-Richtlinientyp* hinzugefügt, die angibt, ob die Richtlinie fest oder adaptiv ist.  Wenn keines von beiden zutrifft, wird in der Spalte _Nicht verfügbar_ angezeigt. Weitere Informationen finden Sie unter link:./integrations/volumes-objects-tab.html["Registerkarte „Volumes und Objekte“"^] .



[[new-column-and-simplified-subscription-display-in-the-volume-summary-tab]]
=== Neue Spalte und vereinfachte Abonnementanzeige im Reiter „Volumenübersicht“

* Die Registerkarte *Volume-Zusammenfassung* innerhalb der Registerkarte *Volumes & Objekte* enthält jetzt eine neue Spalte mit dem Titel *Geschützt*.  Diese Spalte enthält die Anzahl der geschützten Volumes, die mit Ihren abonnierten Service-Levels verknüpft sind.  Wenn Sie auf die Anzahl der geschützten Volumes klicken, gelangen Sie zur Registerkarte *Volumedetails*, auf der Sie eine gefilterte Liste der geschützten Volumes anzeigen können.
* Die Registerkarte *Volume Summary* wurde aktualisiert und zeigt nun nur noch Basisabonnements an, Zusatzdienste sind ausgeschlossen. Weitere Informationen finden Sie unter link:./integrations/volumes-objects-tab.html["Registerkarte „Volumes und Objekte“"^] .




[[change-to-accrued-burst-detail-display-in-the-capacity-trend-tab]]
=== Änderung der Anzeige der aufgelaufenen Burst-Details im Reiter „Kapazitätstrend“

Der Tooltip, der angezeigt wird, wenn Sie mit der Maus über das Balkendiagramm zur Kapazitätsnutzung auf der Registerkarte *Kapazitätstrend* fahren, zeigt die Details der aufgelaufenen Bursts für den aktuellen Monat an.  Für die vorherigen Monate sind keine Details verfügbar.



[[enhanced-access-to-view-historical-data-for-keystone-subscriptions]]
=== Verbesserter Zugriff zum Anzeigen historischer Daten für Keystone -Abonnements

Sie können jetzt historische Daten anzeigen, wenn ein Keystone Abonnement geändert oder erneuert wird.  Sie können das Startdatum eines Abonnements auf ein früheres Datum festlegen, um Folgendes anzuzeigen:

* Daten zum Verbrauch und zur aufgelaufenen Burst-Nutzung von der Registerkarte *Kapazitätstrend*.
* Leistungsmetriken von ONTAP -Volumes aus der Registerkarte *Leistung*.


Die Daten werden basierend auf dem ausgewählten Startdatum des Abonnements angezeigt.



[[29-february-2024]]
== 29. Februar 2024



[[addition-of-the-assets-tab]]
=== Hinzufügen der Registerkarte „Assets“

Der Bildschirm * Keystone -Abonnements* enthält jetzt die Registerkarte *Assets*.  Diese neue Registerkarte bietet Informationen auf Clusterebene basierend auf Ihren Abonnements. Weitere Informationen finden Sie unter link:./integrations/assets-tab.html["Registerkarte „Assets“"^] .



[[improvements-to-the-volumes-objects-tab]]
=== Verbesserungen an der Registerkarte „Volumes & Objekte“

Um eine bessere Übersicht über Ihre ONTAP -Systemvolumes zu gewährleisten, wurden der Registerkarte *Volumes* zwei neue Registerkartenschaltflächen hinzugefügt: *Volume-Zusammenfassung* und *Volume-Details*.  Die Registerkarte *Volume-Zusammenfassung* bietet eine Gesamtzählung der mit Ihren abonnierten Service-Levels verbundenen Volumes, einschließlich ihres AQoS-Konformitätsstatus und Kapazitätsinformationen.  Auf der Registerkarte *Volumedetails* werden alle Volumes und ihre Besonderheiten aufgelistet. Weitere Informationen finden Sie unter link:./integrations/volumes-objects-tab.html["Registerkarte „Volumes und Objekte“"^] .



[[enhanced-search-experience-on-digital-advisor]]
=== Verbessertes Sucherlebnis bei Digital Advisor

Die Suchparameter auf dem Bildschirm „Digital Advisor“ umfassen jetzt Keystone Abonnementnummern und für Keystone -Abonnements erstellte Beobachtungslisten.  Sie können die ersten drei Zeichen einer Abonnementnummer oder eines Beobachtungslistennamens eingeben. Weitere Informationen finden Sie unter link:./integrations/keystone-aiq.html["Sehen Sie sich das Keystone -Dashboard auf Active IQ Digital Advisor an"^] .



[[view-timestamp-of-the-consumption-data]]
=== Zeitstempel der Verbrauchsdaten anzeigen

Sie können den Zeitstempel der Verbrauchsdaten (in UTC) auf dem alten Dashboard des Widgets * Keystone Subscriptions* anzeigen.



[[13-february-2024]]
== 13. Februar 2024



[[ability-to-view-subscriptions-linked-to-a-primary-subscription]]
=== Möglichkeit, Abonnements anzuzeigen, die mit einem primären Abonnement verknüpft sind

Einige Ihrer primären Abonnements können verknüpfte sekundäre Abonnements haben.  In diesem Fall wird die primäre Abonnementnummer weiterhin in der Spalte *Abonnementnummer* angezeigt, während die verknüpften Abonnementnummern in einer neuen Spalte *Verknüpfte Abonnements* auf der Registerkarte *Abonnements* aufgeführt werden.  Die Spalte *Verknüpfte Abonnements* steht Ihnen nur zur Verfügung, wenn Sie verknüpfte Abonnements haben und Sie können Informationsmeldungen sehen, die Sie darüber informieren.



[[11-january-2024]]
== 11. Januar 2024



[[invoiced-data-returned-for-accrued-burst]]
=== Für den aufgelaufenen Burst zurückgegebene Rechnungsdaten

Die Beschriftungen für *Accrued Burst* werden jetzt auf der Registerkarte *Capacity Trend* in *Invoiced Accrued Burst* geändert.  Durch Auswahl dieser Option können Sie die monatlichen Diagramme für die in Rechnung gestellten, aufgelaufenen Burst-Daten anzeigen. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-accrued-burst["Abgerechneten aufgelaufenen Burst anzeigen"^] .



[[accrued-consumption-details-for-specific-rate-plans]]
=== Aufgelaufene Verbrauchsdetails für bestimmte Tarifpläne

Wenn Sie ein Abonnement mit Tarifplänen mit _null_ zugesagter Kapazität haben, können Sie die aufgelaufenen Verbrauchsdetails auf der Registerkarte *Kapazitätstrend* anzeigen.  Wenn Sie die Option *Abgerechneter Verbrauch* auswählen, können Sie die monatlichen Diagramme für die abgerechneten Verbrauchsdaten anzeigen.



[[15-december-2023]]
== 15. Dezember 2023



[[ability-to-search-by-watchlists]]
=== Möglichkeit zur Suche nach Beobachtungslisten

Die Unterstützung für Beobachtungslisten in Digital Advisor wurde auf Keystone -Systeme erweitert.  Sie können jetzt die Details der Abonnements für mehrere Kunden anzeigen, indem Sie mit Beobachtungslisten suchen.  Weitere Informationen zur Verwendung von Beobachtungslisten in Keystone STaaS finden Sie unterlink:./integrations/keystone-aiq.html#search-by-keystone-watchlists["Suche nach Keystone -Beobachtungslisten"^] .



[[date-converted-to-utc-timezone]]
=== Datum in UTC-Zeitzone konvertiert

Die auf den Registerkarten des Bildschirms * Keystone -Abonnements* von Digital Advisor zurückgegebenen Daten werden in UTC-Zeit (Server-Zeitzone) angezeigt.  Wenn Sie ein Datum für die Abfrage eingeben, wird automatisch davon ausgegangen, dass es sich um UTC-Zeit handelt. Weitere Informationen finden Sie unter link:./integrations/keystone-aiq.html["Keystone -Abonnement-Dashboard und -Berichterstellung"^] .
