---
sidebar: sidebar 
permalink: rest-api/get-customer-consumption.html 
keywords: api, consumption, subscriptions, customerID, keystone, Digital Advisor 
summary: Die Digital Advisor REST-API ruft die aktuellen Verbrauchsdetails für alle Abonnements ab, die mit der angegebenen Kunden-ID verknüpft sind. 
---
= Erhalten Sie Details zum Kundenverbrauch mithilfe der Digital Advisor REST-API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Diese API ruft die aktuellen Verbrauchsdetails für alle Abonnements ab, die mit der angegebenen Kunden-ID verknüpft sind.

*Anfrage:*

[cols="24%,76%"]
|===


| *Verfahren* | ERHALTEN 


| *Endpunkt* | `https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details` 


| *Parameter*  a| 
* Typ: "Kunde"
* id: <Kunden-ID>




| *Kopfzeilen*  a| 
* akzeptieren: application/json
* Autorisierungstoken: <Zugriffsschlüssel>


|===
*Antwort:* Die API antwortet mit einem JSON-Objekt, das eine Liste aller Abonnements mit den aktuellen Servicenutzungsmetriken für den angegebenen Kunden enthält.  Hier ist eine Beispielantwort:

[listing]
----
{
"result":  {
"returned_records": "string",
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "string",
"end_date": "string"
},
"service_levels": [
{
"name": "string",
"committed_tib": "string",
"consumed_tib": "string",
"consumed_timestamp_utc": "string",
"burst_tib": "string",
"accrued_burst_tib": "string"
}
]
}
],
"request_id": "string",
"response_time": "string"
}
}
----
*Statuscode*: 200 – Erfolgreiche Anfrage

*Curl-Beispiel*:

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details?type=customer&id=<customerID>' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----


== Erhalten Sie die historischen Verbrauchsdetails für einen Kunden

Diese API ruft die historischen Verbrauchsdetails für alle Abonnements ab, die mit der angegebenen Kunden-ID im angegebenen Zeitraum verknüpft sind.

*Anfrage:*

[cols="24%,76%"]
|===


| *Verfahren* | ERHALTEN 


| *Endpunkt* | `https://api.activeiq.netapp.com/v1/keystone/customer/historical-consumption-details` 


| *Parameter*  a| 
* Typ: "Kunde"
* id: <Kunden-ID>
* from_date_utc: <Startdatum (im RFC3339-Format)>
* to_date_utc: <Enddatum (im RFC3339-Format)>




| *Kopfzeilen*  a| 
* akzeptieren: application/json
* Autorisierungstoken: <Zugriffsschlüssel>


|===
*Antwort:*

Die API antwortet mit einem JSON-Objekt, das eine Liste aller Abonnements mit den historischen Dienstnutzungsmetriken für den angegebenen Kunden im ausgewählten Zeitraum enthält.  Hier ist eine Beispielantwort:

[listing]
----
{
"results":  {
"returned_records": 0,
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "2023-08-24T14:15:22Z",
"end_date": "2023-08-24T14:15:22Z"
},
"service_levels": [
{
"name": "string",
"historical_consumption": [
{
"committed_tib": 0,
"consumed_tib": 0,
"timestamp_utc": "2023-08-24T14:15:22Z",
"burst_tib": 0,
"accrued_burst_tib": 0,
"is_invoiced": true
}
]
}
]
}
],
"request_parameters":  {
"from_date_utc": "2023-08-24",
"to_date_utc": "2023-08-24",
"customer_id": "string"
},
"request_id": "string",
"response_time": "string",
"customer":  {
"name": "string",
"id": "string"
}
}
}
----
*Statuscode*: 200 – Erfolgreiche Anfrage

*Curl-Beispiel*:

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq-stg.netapp.com/v1/keystone/customer/historical-consumption-details? type=customer&id=<customerID>&from_date_utc=2023-08-24T14%3A15%3A22Z&t _date_utc=2023-08-24T14%3A15%3A22Z' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----