---
sidebar: sidebar 
permalink: rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html 
keywords: Keystone, Active IQ, Digital Advisor, APIs, programmatic interface 
summary: Digital Advisor -APIs bieten eine programmgesteuerte Schnittstelle zum Abrufen von Keystone -Servicedetails und -Metriken. 
---
= Erste Schritte mit der Digital Advisor REST-API zum Abrufen von Keystone -Daten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Digital Advisor REST-API bietet eine programmgesteuerte Schnittstelle zum Abrufen von Keystone Abonnement- und Verbrauchsdetails.

Auf hoher Ebene umfasst der Workflow zur Interaktion mit der Digital Advisor REST-API die folgenden Schritte:

. Richten Sie Ihr Digital Advisor -Konto ein.  Sie müssen über gültige Anmeldeinformationen für die NetApp Support-Site verfügen, um sich bei Digital Advisor anzumelden.  Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/active-iq/task_login_activeiq.html["Melden Sie sich bei Digital Advisor an."]
. Verstehen Sie den zweistufigen Authentifizierungsprozess.
+
.. *Erstellen eines Aktualisierungstokens*: Ein Aktualisierungstoken wird über die Digital Advisor Konsole mithilfe der NetApp Anmeldeinformationen abgerufen. Dieses Token wird verwendet, um einen kontinuierlichen Zugriff ohne wiederholte Anmeldungen zu gewährleisten.
.. *Zugriffstoken generieren*: Das Aktualisierungstoken wird zum Generieren von Zugriffstoken verwendet.  Zur Autorisierung von API-Aufrufen an den Keystone -Dienst ist ein Zugriffstoken erforderlich, das eine Stunde lang gültig ist.


. Führen Sie einen API-Aufruf aus, um die gewünschten Daten abzurufen. Sie können Kundenlisten, Kundenabonnementdaten und Kundenverbrauchsdetails programmgesteuert abrufen.

