---
sidebar: sidebar 
permalink: concepts/committed-capacity-billing.html 
keywords: Billing based on committed capacity, committed capacity billing 
summary: Bei der zugesagten Kapazität handelt es sich um die Kapazität, die beim Kauf des Abonnements für ein bestimmtes Servicelevel zugesagt wurde. 
---
= Keystone Abrechnung der zugesagten Kapazität verstehen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei der zugesagten Kapazität handelt es sich um die Kapazität, die beim Kauf des Abonnements für ein bestimmtes Leistungsservicelevel zugesagt wurde.

Die zugesagte Kapazität kann die Gesamtkapazität für verschiedene Leistungsservicelevel in einem einzigen Abonnement sein, wie von Ihnen und NetApp/Partner akzeptiert.  Diese Kapazität wird auf jeder Keystone -Bestellung angegeben und unabhängig vom tatsächlichen Kapazitätsverbrauch in Rechnung gestellt.

Informationen zu den verschiedenen in Keystone unterstützten Kapazitäten finden Sie unterlink:../concepts/supported-storage-capacity.html["Unterstützte Speicherkapazitäten in Keystone"] .
