---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone bietet ein Pay-as-you-grow-Modell für Ihren flexiblen und skalierbaren Verbrauchsbedarf. 
---
= Erfahren Sie mehr über die Keystone-Abrechnung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit NetApp Keystone STaaS zahlen Sie für das, was Sie buchen, und nur zusätzlich für das, was Sie darüber hinaus nutzen. Diese Seite erklärt, wie das Pay-as-you-go-Modell funktioniert, einschließlich wie Ihr Speicherkontingent bepreist wird, wie die Kapazität gemessen und abgerechnet wird und wann Rechnungen erstellt werden.



[[keystone-pricing-model]]
== Keystone-Preismodell

Mit Ihrem Keystone-Abonnement profitieren Sie von planbaren Kosten und der Flexibilität, bei Bedarf zu skalieren. Die Keystone-Gebühren richten sich nach dem von Ihnen gewählten Leistungsservicelevel und der Kapazität, zu der Sie sich verpflichten.

Keystone bietet Ihnen die folgenden Abrechnungsmöglichkeiten:

* Sie können basierend auf der zugesicherten Kapazität für IOPS und Latenz bezahlen, um unterschiedliche Workload-Anforderungen zu erfüllen. Die verschiedenen Leistungsservice-Tiers – Extreme, Premium, Standard, Value, Object und Cloud Volumes ONTAP – ermöglichen Ihnen, Ihren Speicher entsprechend Ihrer erworbenen Leistungsservice-Stufe zu verwalten.
* Es bietet eine vorhersehbare Abrechnung für die zugesagte Kapazität und eine nutzungsabhängige Bezahlung für die variable (Burst-)Kapazitätsnutzung.
* Sie können ein Paketangebot für Hardware, Core-OS und Support zu einem Preis von $/TiB auswählen. Sie erhalten eine einzige Rechnung für jeden Speichertyp: einheitlich, Block, optimiert, Objekt oder Cloud-Speicherdienste.
* Sie können eine flexible Laufzeit für die Services und Zahlungsoptionen wählen, z. B. monatlich, vierteljährlich, halbjährlich oder jährlich.


Die Keystone -Abrechnung basiert auf der zugesagten Kapazität und dem variablen Burst-Verbrauch.

Informationen zu den verschiedenen Kapazitäten, die in Keystone unterstützt werden, finden Sie unter link:../concepts/supported-storage-capacity.html["Speicherkapazitätstypen in Keystone"].



[[how-keystone-measures-capacity]]
== Wie Keystone die Kapazität misst

Keystone verwendet drei Kapazitätskonzepte zur Berechnung Ihrer Rechnung. Wenn Sie diese kennen, können Sie unerwartete Gebühren vermeiden.



[[committed-capacity]]
=== Zugesicherte Kapazität

Die zugesicherte Kapazität ist die Kapazität, die Sie für ein bestimmtes Leistungsniveau beim Abschluss Ihres Keystone-Abonnements erwerben. Dieser Betrag ist in Ihrer Keystone-Bestellung festgelegt und wird in jeder Abrechnungsperiode vollständig in Rechnung gestellt, unabhängig davon, wie viel Kapazität Ihre Workloads tatsächlich nutzen.

Wenn Sie sich beispielsweise für 100 TiB auf der Premium-Serviceebene verpflichten, werden Ihnen 100 TiB in Rechnung gestellt, selbst wenn die tatsächliche Nutzung in diesem Monat 80 TiB beträgt.

Die zugesicherte Kapazität kann sich über mehrere Leistungsstufen innerhalb eines einzigen Abonnements erstrecken, wie von Ihnen und NetApp oder Ihrem Partner vereinbart.

Um Ihre zugesagte Kapazität einzusehen und die tatsächliche Nutzung im Vergleich dazu zu verfolgen, siehe link:../integrations/current-usage-tab.html["Sehen Sie sich Ihre aktuellen Verbrauchsdetails an"].



[[consumed-capacity]]
=== Verbrauchte Kapazität

Die tatsächlich genutzte Kapazität ist die Kapazität, die Ihre Workloads zu jedem Zeitpunkt nutzen. Keystone überwacht und misst Ihren Verbrauch kontinuierlich während des gesamten Abrechnungszeitraums. Mindestens alle fünf Minuten wird ein Verbrauchsdatensatz erstellt, der die aktuell genutzte Kapazität Ihres Abonnements erfasst. Diese Datensätze werden über den Abrechnungszeitraum aggregiert, um Rechnungen und Nutzungsberichte zu erstellen.

Das fünfminütige Überwachungsintervall gewährleistet eine detaillierte Nachverfolgung, sodass Spitzenverbrauch genau erkannt und abgerechnet wird – und nicht am Ende des Zeitraums geschätzt wird.

Solange die genutzte Kapazität der zugesicherten Kapazität entspricht oder darunter liegt, gilt nur der Tarif für die zugesicherte Kapazität. Sobald die genutzte Kapazität die zugesicherte Kapazität überschreitet, gilt die Burst-Abrechnung.



[[burst-consumption]]
=== Burst Consumption

Burst-Verbrauch ist die Kapazität, die Sie über Ihre zugesicherte Kapazität hinaus nutzen. Ihr Burst-Limit wird in Ihrem Keystone-Vertrag festgelegt und spezifiziert. Es liegt 20 % über der zugesicherten Kapazität.

Wenn Ihre zugesicherte Kapazität beispielsweise 100 TiB beträgt und Sie 115 TiB nutzen, werden die zusätzlichen 15 TiB zum Burst-Tarif abgerechnet.

Wenn die verbrauchte Kapazität die für ein Leistungsniveau zugesicherte Kapazität übersteigt, wird der Spitzenverbrauch erfasst und entsprechend abgerechnet. Eine Nutzung oberhalb des Spitzenkapazitätslimits wird als „Über dem Spitzenkapazitätslimit“ gekennzeichnet.

Der Spitzenverbrauch wird für jeden Verbrauchsdatensatz berechnet, der während des Abrechnungszeitraums generiert wird. Er spiegelt sowohl die Menge als auch die Dauer Ihrer über die vertraglich vereinbarte Kapazität hinausgehenden Übernutzung wider. Um die Trends des Spitzenverbrauchs für Ihr Abonnement anzuzeigen, siehe link:../integrations/consumption-tab.html["Verbrauchstrends Ihrer Keystone -Abonnements anzeigen"].



[[billing-schedules]]
== Abrechnungspläne

Die Abrechnungshäufigkeit ist in Ihrem Keystone-Vertrag festgelegt. Die folgende Tabelle zeigt, wann Sie mit Rechnungen für die zugesicherte Kapazität und die Spitzennutzung im Rahmen der jeweiligen Optionen rechnen können.

[cols="1,2,2"]
|===
| Abrechnungshäufigkeit | Rechnung für zugesagte Kapazität | Rechnung für Spitzennutzung 


| Monatlich | Im Folgemonat versandt | Auf derselben Rechnung enthalten 


| Jährlich | Wird zu Beginn jedes Abonnementjahres versandt | Wird am Ende jedes Quartals versandt 
|===

NOTE: Bei jährlicher Abrechnung wird Ihnen im Falle einer Änderung Ihrer zugesagten Kapazität während der Laufzeit Ihres Abonnements am selben Tag eine Rechnung über die anteiligen Mindestzahlungen für den Rest des Abonnementjahres zugesandt. Die Abrechnung beginnt mit dem Tag, an dem die Änderung der zugesagten Kapazität wirksam wird.



[[related-information]]
== Verwandte Informationen

* link:../concepts/supported-storage-capacity.html["Speicherkapazitätstypen in Keystone"]
* link:../integrations/current-usage-tab.html["Sehen Sie sich Ihre aktuellen Verbrauchsdetails an"]
* link:../integrations/consumption-tab.html["Verbrauchstrends Ihrer Keystone -Abonnements anzeigen"]

