---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Informieren Sie sich über die Speicherkapazitätstypen, die vom NetApp Keystone STaaS-Dienst für Version 2 unterstützt werden. 
---
= Unterstützte Speicherkapazitäten in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Der NetApp Keystone STaaS-Dienst unterstützt mehrere Arten von Speicherkapazitäten.  Das Verständnis dieser unterschiedlichen Kapazitätsbegriffe kann Ihnen bei der Verwendung von Keystone helfen.



[[logical-capacity]]
== Logische Kapazität

Dies ist die Speicherkapazität, die erforderlich ist, um Benutzerdaten zu speichern, bevor die vom Speichersystem bereitgestellten Dateneffizienzen angewendet werden.



[[committed-capacity]]
== Zugesicherte Kapazität

Die monatlich während der Abonnementlaufzeit in Rechnung gestellte Mindestkapazität:

* Für jedes Leistungsservicelevel ist Kapazität festgelegt.
* Während der Laufzeit können feste Kapazitäten und zusätzliche Service-Levels hinzugefügt werden.




[[changes-to-committed-capacity]]
=== Änderungen der zugesagten Kapazität

Während der Laufzeit eines Abonnements können Sie die zugesagten Kapazitäten ändern.  Allerdings gibt es bestimmte Voraussetzungen:

* Die zugesagte Kapazität kann unter bestimmten Bedingungen verringert werden.  Weitere Informationen finden Sie unterlink:../concepts/capacity-requirements.html["Kapazitätsreduzierung"] .
* Die zugesagte Kapazität kann 90 Tage vor Ablauf Ihres Abonnements nicht erhöht werden, es sei denn, das Abonnement soll um weitere 12 Monate verlängert werden.
* Änderungen der zugesagten Kapazität können Sie über die Konsole oder über Ihren Keystone Success Manager (KSM) anfordern. Informationen zum Beantragen von Änderungen finden Sie unter link:../concepts/support-services.html["NetApp Keystone Unterstützung"]Die




[[consumed-capacity]]
== Verbrauchte Kapazität

Die belegte Kapazität bezieht sich auf die Kapazität (in TiB Speicher), die aktuell vom Dienst genutzt wird. Sie wird je nach Datenspeichertyp unterschiedlich berechnet:

* *Einheitlicher oder blockoptimierter Speicher*: Die verbrauchte Kapazität wird basierend auf dem während des Bestellprozesses ausgewählten Kapazitätstyps (entweder logisch oder physisch) berechnet. Die Berechnung erfolgt pro Performance-Servicelevel-Instanz.
+
.. *Logische Kapazität*: Sie ist die Summe aus:
+
*** Gemessene logische Kapazität, vor der Dateneffizienz des Storage Arrays, um alle Instanzen und Arten von Kundendaten zu speichern, wie Kopien, gespiegelte Kopien, Versionen und Klone.
*** Physische Kapazität zur Speicherung von Metadaten und Differenzdaten von Snapshots und bestimmten Klonen.
*** Jede dick bereitgestellte physische Kapazität.


.. *Physische Kapazität*: Sie ist die Summe aus:
+
*** Gemessene physische Kapazität, nach Berücksichtigung der Dateneffizienz des Storage Arrays, zur Speicherung aller Instanzen und Arten von Kundendaten, wie Kopien, gespiegelte Kopien, Versionen und Klone.
*** Physische Kapazität, die zur Speicherung von Metadaten und Differenzdaten von Snapshots verwendet wird.
*** Jede dick bereitgestellte physische Kapazität.




* *Objektspeicher*: Die belegte Kapazität wird als die Menge der gemessenen physischen Kapazität berechnet, die zum Speichern aller Instanzen und Typen von Kundendaten auf allen Knoten verwendet wird. Diese Berechnung basiert auf den konfigurierten Richtlinien für das Informationslebenszyklusmanagement (ILM).
* *Cloud Volumes ONTAP*: Die verbrauchte Kapazität wird als die Menge der gemessenen, bereitgestellten logischen Kapazität aller Cloud Volumes ONTAP Volumes berechnet.




[[burst-capacity]]
== Burst-Kapazität

Mit dem NetApp Keystone Service können Sie zusätzlich zur zugesagten Kapazität für ein Servicelevel zusätzliche Kapazität nutzen.  Dies wird als Burst-Kapazitätsnutzung bezeichnet.

Beachten Sie diese Punkte:

* Die Burst-Kapazität wird im Keystone Abkommen vereinbart.  Sie liegt normalerweise bei bis zu 20 % über der zugesagten Kapazität und wird zum gleichen Satz wie die zugesagte Kapazität berechnet.
* Die Burst-Kapazität kann elastisch verbraucht werden und wird täglich für den verbrauchten Durchschnitt berechnet.




[[billed-capacity]]
== Abgerechnete Kapazität

Monatliche Rechnung = (zugesagte Kapazität [TiB] * zugesagte Rate [$/TiB]) + (täglich durchschnittlich bereitgestellte Burst-Kapazität [TiB] * Burst-Rate [$/TiB]).  Die monatliche Rechnung enthält eine Mindestgebühr basierend auf der zugesagten Kapazität.

Die monatliche Rechnung variiert über die Mindestgebühr hinaus basierend auf dem täglichen durchschnittlichen Burst-Kapazitätsverbrauch.
