---
sidebar: sidebar 
permalink: installation/linux-prereqs.html 
keywords: prerequisites, Linux 
summary: Bereiten Sie Ihr Linux-System mit der erforderlichen Software vor, bevor Sie Keystone Collector installieren. 
---
= Linux-Anforderungen für Keystone Collector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durch die Vorbereitung Ihres Linux-Systems mit der erforderlichen Software wird eine präzise Installation und Datenerfassung durch Keystone Collector gewährleistet.

Stellen Sie sicher, dass Ihre Linux- und Keystone Collector-Server-VM über diese Konfigurationen verfügt.

.Linux-Server:
* Betriebssystem: Eines der folgenden:
+
** Debian 12
** Red Hat Enterprise Linux 8.6 oder höher 8.x-Versionen
** Red Hat Enterprise Linux 9.0 oder spätere Versionen
** CentOS 7 (nur für bestehende Umgebungen)


* Chronyd Zeit synchronisiert
* Zugriff auf die Standard-Linux-Software-Repositorys


Derselbe Server sollte auch über die folgenden Pakete von Drittanbietern verfügen:

* podman (POD-Manager)
* SOS
* Chroniken
* Python 3 (3.9.14 bis 3.11.8)


.Keystone Collector-Server-VM:
* Kern: 2 CPUs
* Arbeitsspeicher: 4 GB RAM
* Speicherplatz: 50 GB vDisk




== Sonstige Anforderungen

Stellen Sie sicher, dass die folgenden allgemeinen Anforderungen erfüllt sind:



=== Netzwerkanforderungen

Die Netzwerkanforderungen von Keystone Collector sind in der folgenden Tabelle aufgeführt.


NOTE: Keystone Collector erfordert eine Internetverbindung.  Sie können die Internetverbindung durch direktes Routing über das Standard-Gateway (über NAT) oder über einen HTTP-Proxy bereitstellen.  Beide Varianten werden hier beschrieben.

|===


| Quelle | Ziel | Service | Protokoll und Ports | Kategorie | Zweck 


 a| 
Keystone Collector (für Keystone ONTAP)
 a| 
Active IQ Unified Manager (Unified Manager)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorisch (bei Verwendung von Keystone ONTAP)
 a| 
Keystone Collector-Nutzungsmetrikenerfassung für ONTAP



 a| 
Keystone Collector (für Keystone StorageGRID)
 a| 
StorageGRID -Admin-Knoten
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorisch (bei Verwendung von Keystone StorageGRID)
 a| 
Erfassung von Keystone Collector-Nutzungsmetriken für StorageGRID



 a| 
Keystone Collector (generisch)
 a| 
Internet (gemäß den später angegebenen URL-Anforderungen)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorisch (Internetverbindung)
 a| 
Keystone Collector-Software, Betriebssystem-Updates und Metrik-Upload



 a| 
Keystone Collector (generisch)
 a| 
Kunden-HTTP-Proxy
 a| 
HTTP-Proxy
 a| 
Kunden-Proxy-Port
 a| 
Obligatorisch (Internetverbindung)
 a| 
Keystone Collector-Software, Betriebssystem-Updates und Metrik-Upload



 a| 
Keystone Collector (generisch)
 a| 
Kunden-DNS-Server
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
Obligatorisch
 a| 
DNS-Auflösung



 a| 
Keystone Collector (generisch)
 a| 
Kunden-NTP-Server
 a| 
NTP
 a| 
UDP 123
 a| 
Obligatorisch
 a| 
Zeitsynchronisation



 a| 
Keystone Collector (für Keystone ONTAP)
 a| 
Einheitlicher Manager
 a| 
MySQL
 a| 
TCP 3306
 a| 
Optionale Funktionalität
 a| 
Erfassung von Leistungsmetriken für Keystone Collector



 a| 
Keystone Collector (generisch)
 a| 
Kundenüberwachungssystem
 a| 
HTTPS
 a| 
TCP 7777
 a| 
Optionale Funktionalität
 a| 
Integritätsberichte für Keystone Collector



 a| 
Betriebsarbeitsplätze des Kunden
 a| 
Keystone -Sammler
 a| 
SSH
 a| 
TCP 22
 a| 
Management
 a| 
Zugriff auf die Keystone Collector-Verwaltung



 a| 
NetApp ONTAP Cluster- und Node-Management-Adressen
 a| 
Keystone -Sammler
 a| 
HTTP_8000, PING
 a| 
TCP 8000, ICMP-Echoanforderung/-antwort
 a| 
Optionale Funktionalität
 a| 
Webserver für ONTAP -Firmware-Updates

|===

NOTE: Der Standardport für MySQL, 3306, ist während einer Neuinstallation von Unified Manager nur auf localhost beschränkt, was die Erfassung von Leistungsmetriken für Keystone Collector verhindert. Weitere Informationen finden Sie unter link:addl-req.html["ONTAP Anforderungen"] .



=== URL-Zugriff

Keystone Collector benötigt Zugriff auf die folgenden Internet-Hosts:

|===


| Adresse | Grund 


 a| 
https://keystone.netapp.com[]
 a| 
Keystone Collector-Software-Updates und Nutzungsberichte



 a| 
https://support.netapp.com[]
 a| 
NetApp HQ für Rechnungsinformationen und AutoSupport Bereitstellung

|===