---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Bekannte Probleme identifizieren Probleme, die Sie möglicherweise daran hindern, die Keystone -Abonnementdienste effektiv zu nutzen. 
---
= Bekannte Probleme in Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die Sie möglicherweise daran hindern, die Keystone -Abonnementdienste effektiv zu nutzen.

Die folgenden bekannten Probleme wurden in NetApp Keystone STaaS gemeldet:

[cols="3*"]
|===
| Bekanntes Problem | Beschreibung | Problemumgehung 


 a| 
Falsche Rechnung aufgrund von Datenkonflikten
 a| 
Eine Nichtübereinstimmung der Verbrauchsdaten für AutoSupport Abonnements führt zur Erstellung falscher Rechnungen und damit zu Abrechnungsungenauigkeiten.
 a| 
Keine



 a| 
Falsche Anzeige des QoS-Richtlinientyps
 a| 
Auf der Registerkarte *Volumedetails* wird in der Spalte *QoS-Richtlinientyp* _QoS_ angezeigt, wenn keine QoS-Richtlinie angewendet wird, und in der Spalte „Konform“ wird _Nicht festgelegt_ angezeigt, was zu einer Inkonsistenz im angezeigten QoS-Richtlinienstatus führt.
 a| 
Keine



 a| 
Volumendetails für primäre und verknüpfte Abonnements nicht verfügbar
 a| 
Auf der Registerkarte *Volume-Zusammenfassung* wird Null für die Gesamtzahl der Volumes, den QoS-Konformitätsstatus, die Anzahl der geschützten Volumes und die insgesamt verbrauchte Kapazität für primäre und verknüpfte sekundäre Abonnements angezeigt.
 a| 
Keine

|===